-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CAR_RENTAL
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CAR_RENTAL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CAR_RENTAL` DEFAULT CHARACTER SET utf8 ;
USE `CAR_RENTAL` ;

-- -----------------------------------------------------
-- Table `CAR_RENTAL`.`OFFICE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAR_RENTAL`.`OFFICE` (
  `OFFICE_ID` INT NOT NULL,
  `OFFICE_STREET` VARCHAR(45) NOT NULL,
  `OFFICE_CITY` VARCHAR(15) NOT NULL,
  `OFFICE_STATE` VARCHAR(2) NOT NULL,
  `OFFICE_ZIPCODE` INT NOT NULL,
  `OFFICE_AREACODE` INT NOT NULL,
  `OFFICE_PHONE` INT NOT NULL,
  PRIMARY KEY (`OFFICE_ID`),
  UNIQUE INDEX `OFFICE_ID_UNIQUE` (`OFFICE_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAR_RENTAL`.`PERSON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAR_RENTAL`.`PERSON` (
  `PERSON_ID` INT NOT NULL,
  `PERSON_LNAME` VARCHAR(15) NOT NULL,
  `PERSON_FNAME` VARCHAR(15) NOT NULL,
  `PERSON_MNAME` VARCHAR(15) NULL,
  `PERSON_STREET` VARCHAR(20) NOT NULL,
  `PERSON_CITY` VARCHAR(15) NOT NULL,
  `PERSON_STATE` VARCHAR(2) NOT NULL,
  `PERSON_ZIPCODE` INT NOT NULL,
  `PERSON_DOB` DATE NOT NULL,
  `PERSON_AREACODE` INT NOT NULL,
  `PERSON_PHONE` INT NOT NULL,
  `PERSON_USERNAME` VARCHAR(15) NOT NULL,
  `PERSON_PASSWORD` VARCHAR(20) NOT NULL,
  `PERSON_EMAILID` VARCHAR(20) NOT NULL,
  `PERSON_EMAILDOMAIN` VARCHAR(20) NOT NULL,
  `PERSON_GENDER` VARCHAR(20) NULL,
  `PERSON_TYPE` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`PERSON_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAR_RENTAL`.`CUSTOMER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAR_RENTAL`.`CUSTOMER` (
  `PERSON_ID` INT NOT NULL,
  `OFFICE_ID` INT NOT NULL,
  `CUSTOMER_CREDITCARD` INT NOT NULL,
  PRIMARY KEY (`PERSON_ID`),
  INDEX `fk_CUSTOMER_OFFICE1_idx` (`OFFICE_ID` ASC) VISIBLE,
  UNIQUE INDEX `CUSTOMER_CREDITCARD_UNIQUE` (`CUSTOMER_CREDITCARD` ASC) VISIBLE,
  INDEX `fk_CUSTOMER_PERSONNEL1_idx` (`PERSON_ID` ASC) VISIBLE,
  CONSTRAINT `CUSTOMER_OFFICE_ID`
    FOREIGN KEY (`OFFICE_ID`)
    REFERENCES `CAR_RENTAL`.`OFFICE` (`OFFICE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CUSTOMER_PERSONNE_ID`
    FOREIGN KEY (`PERSON_ID`)
    REFERENCES `CAR_RENTAL`.`PERSON` (`PERSON_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAR_RENTAL`.`CAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAR_RENTAL`.`CAR` (
  `CAR_ID` INT NOT NULL,
  `OFFICE_ID` INT NOT NULL,
  `CAR_BRAND` VARCHAR(15) NOT NULL,
  `CAR_YEAR` INT NOT NULL,
  `CAR_COLOR` VARCHAR(10) NOT NULL,
  `CAR_FUEL_EFFICIENCY` INT NOT NULL,
  `CAR_BODYSTYLE` VARCHAR(15) NOT NULL,
  `CAR_DRIVETYPE` VARCHAR(15) NOT NULL,
  `CAR_TRANSMISSION` VARCHAR(1) NOT NULL,
  `CAR_ENGINE` VARCHAR(10) NOT NULL,
  `CAR_TRIM` VARCHAR(10) NOT NULL,
  `CAR_MILEAGE` INT NOT NULL,
  `CAR_RENT` INT NOT NULL,
  `CAR_CONDITION` VARCHAR(50) NOT NULL,
  `CAR_AVAILABILITY` INT NOT NULL,
  `PERSON_ID` INT NOT NULL,
  PRIMARY KEY (`CAR_ID`),
  UNIQUE INDEX `CAR_ID_UNIQUE` (`CAR_ID` ASC) VISIBLE,
  INDEX `fk_OFFICE_ID_idx` (`OFFICE_ID` ASC) VISIBLE,
  INDEX `CAR_PERSON_ID_idx` (`PERSON_ID` ASC) VISIBLE,
  CONSTRAINT `CAR_OFFICE_ID`
    FOREIGN KEY (`OFFICE_ID`)
    REFERENCES `CAR_RENTAL`.`OFFICE` (`OFFICE_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `CAR_PERSON_ID`
    FOREIGN KEY (`PERSON_ID`)
    REFERENCES `CAR_RENTAL`.`CUSTOMER` (`PERSON_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAR_RENTAL`.`CAR_DEALERSHIP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAR_RENTAL`.`CAR_DEALERSHIP` (
  `DEALERSHIP_ID` INT NOT NULL,
  `DEALERSHIP_NAME` VARCHAR(45) NOT NULL,
  `DEALERSHIP_LOCATION` VARCHAR(45) NOT NULL,
  `DEALERSHIP_AREACODE` INT NOT NULL,
  `DEALERSHIP_PHONE` INT NOT NULL,
  `DEALERSHIP_COST` INT NOT NULL,
  PRIMARY KEY (`DEALERSHIP_ID`),
  UNIQUE INDEX `DEALERSHIP_ID_UNIQUE` (`DEALERSHIP_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAR_RENTAL`.`EMPLOYEE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAR_RENTAL`.`EMPLOYEE` (
  `PERSON_ID` INT NOT NULL,
  `OFFICE_ID` INT NOT NULL,
  PRIMARY KEY (`PERSON_ID`),
  INDEX `fk_EMPLOYEE_PERSONNEL1_idx` (`PERSON_ID` ASC) VISIBLE,
  CONSTRAINT `EMPLOYEE_OFFICE_ID`
    FOREIGN KEY (`OFFICE_ID`)
    REFERENCES `CAR_RENTAL`.`OFFICE` (`OFFICE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `EMPLOYEE_PERSONNEL_ID`
    FOREIGN KEY (`PERSON_ID`)
    REFERENCES `CAR_RENTAL`.`PERSON` (`PERSON_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `EMPLOYEE_MANAGER`
    FOREIGN KEY (`PERSON_ID`)
    REFERENCES `CAR_RENTAL`.`EMPLOYEE` (`PERSON_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAR_RENTAL`.`BALANCE_SHEET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAR_RENTAL`.`BALANCE_SHEET` (
  `BALANCE_ID` INT NOT NULL,
  `OFFICE_ID` INT NOT NULL,
  `BAL_ASSETS` INT NOT NULL,
  `BAL_LIABILITIES` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`BALANCE_ID`),
  UNIQUE INDEX `OFFICE_ID_UNIQUE` (`OFFICE_ID` ASC) VISIBLE,
  UNIQUE INDEX `BALANCE_ID_UNIQUE` (`BALANCE_ID` ASC) VISIBLE,
  CONSTRAINT `BAL_OFFICE_ID`
    FOREIGN KEY (`OFFICE_ID`)
    REFERENCES `CAR_RENTAL`.`OFFICE` (`OFFICE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAR_RENTAL`.`INCOME_SHEET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAR_RENTAL`.`INCOME_SHEET` (
  `INC_ID` INT NOT NULL,
  `OFFICE_ID` INT NOT NULL,
  `INC_REVENUE` INT NOT NULL,
  `INC_RENT` INT NOT NULL,
  `INC_MAINTAINENCE` INT NOT NULL,
  PRIMARY KEY (`INC_ID`),
  UNIQUE INDEX `OFFICE_ID_UNIQUE` (`OFFICE_ID` ASC) VISIBLE,
  UNIQUE INDEX `INC_ID_UNIQUE` (`INC_ID` ASC) VISIBLE,
  CONSTRAINT `INC_OFFICE_ID`
    FOREIGN KEY (`OFFICE_ID`)
    REFERENCES `CAR_RENTAL`.`OFFICE` (`OFFICE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAR_RENTAL`.`SUPPLIED_BY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAR_RENTAL`.`SUPPLIED_BY` (
  `OFFICE_ID` INT NOT NULL,
  `DEALERSHIP_ID` INT NOT NULL,
  PRIMARY KEY (`OFFICE_ID`, `DEALERSHIP_ID`),
  INDEX `fk_OFFICE_has_CAR_DEALERSHIP_OFFICE1_idx` (`OFFICE_ID` ASC) VISIBLE,
  INDEX `fk_OFFICE_has_CAR_DEALERSHIP_CAR_DEALERSHIP1_idx` (`DEALERSHIP_ID` ASC) VISIBLE,
  CONSTRAINT `SUPPLY_OFFICE_ID`
    FOREIGN KEY (`OFFICE_ID`)
    REFERENCES `CAR_RENTAL`.`OFFICE` (`OFFICE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SUPLLY_DEALERSHIP_ID`
    FOREIGN KEY (`DEALERSHIP_ID`)
    REFERENCES `CAR_RENTAL`.`CAR_DEALERSHIP` (`DEALERSHIP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAR_RENTAL`.`JOB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAR_RENTAL`.`JOB` (
  `JOB_ID` INT NOT NULL,
  `JOB_TITLE` VARCHAR(45) NOT NULL,
  `JOB_SALARY` INT NOT NULL,
  `PERSON_ID` INT NOT NULL,
  PRIMARY KEY (`JOB_ID`),
  INDEX `fk_JOB_EMPLOYEE1_idx` (`PERSON_ID` ASC) VISIBLE,
  UNIQUE INDEX `JOB_TITLE_UNIQUE` (`JOB_TITLE` ASC) VISIBLE,
  CONSTRAINT `JOB_EMPLOYEE_ID`
    FOREIGN KEY (`PERSON_ID`)
    REFERENCES `CAR_RENTAL`.`EMPLOYEE` (`PERSON_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
